### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by levisweetbreu** [mindearth/mobilkit#4]
@takayabe0505 can you point me towards any tests either in the source code or described in the documentation that help the user verify the results of the software functionality?

https://github.com/openjournals/joss-reviews/issues/5201

**Comment by ubi15** [comment]
Hi @levisweetbreu, at the time being there are no automatic tests in the code. The reference for the user is in the tutorial notebook [mobilkit_tutorial.ipynb](https://github.com/mindearth/mobilkit/blob/main/docs/examples/mobilkit_tutorial.ipynb) to check on an open dataset that the code is running as expected.

Please let me know if you need other info.

**Comment by levisweetbreu** [comment]
@ubi15 I'll accept the manual steps you have shown as it falls under the 'OK' section of the [JOSS review guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html). However, I strongly recommend adding automated tests so that the user can verify each function in `mobilkit` works as intended especially when new features are added or the source code is modified. See [this repository](https://github.com/adrn/gala/tree/main) which has a good example of an automated test suite.
