### ISSUE TITLE
Author Contributions

### ISSUE THREAD

**Issue by levisweetbreu** [mindearth/mobilkit#5]
@takayabe0505 or @ubi15 could you give me a brief description of each author's contribution to the software/paper?

https://github.com/openjournals/joss-reviews/issues/5201

**Comment by takayabe0505** [comment]
Sure, here it is:
Enrico Ubaldi -- code development, data analysis, visualization, writing
Takahiro Yabe -- code development, data analysis, visualization, writing
Nicholas Jones -- data analysis, review of writing, supervision
Maham Faisal Khan -- data analysis, review of writing
Alessandra Feliciotti -- data analysis, review of writing
Riccardo Di Clemente -- data analysis, review of writing
Satish V. Ukkusuri -- data analysis, review of writing, supervision
Emanuele Strano -- data analysis, review of writing, supervision
